name = "Hugo Initio"
license = "MIT"
licenselink = "https://github.com/nioupola/hugo-initio/blob/main/LICENSE.md"
description = ""
homepage = "https://sl-japan.jp/"
tags = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.68.3"

[author]
  name = "Nicolas LE GALL"
  homepage = "https://sl-japan.jp/"

[original]
  name = "Hugo Initio"
  author = "Miguel Simoni"
  homepage = "https://miguelsimoni.xyz/"
  repo = "https://github.com/miguelsimoni/hugo-initio/"
